apt-get update before install
Update the workflow example for Github Actions to fix an issue where if
the base image is out of date, the `apt-get install` fails with missing
resources since it's looking for a package that no longer is available
for the new base image.

I was hit by this recently with errors that looked like:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler118_22.02.0-2ubuntu0.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler-glib8_22.02.0-2ubuntu0.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```